### ISSUE TITLE
Mirrors down.

### ISSUE THREAD

**Issue by ar-cyber** [phoenixbyrd/TwisterOS#36]
Hi Phoenixbyrd,

Your mirrors seem to be inaccessible.

**Comment by phoenixbyrd** [comment]
Unfortunately I don't control the mirrors. Those were maintained by another user and were made available because people complained that the main archive.org download links were too slow. I'll try and contact the guy who maintained the mirror downloads and ask what happened. Might just have to remove the mirror downloads for the time being though.
